### ISSUE TITLE
Partial import

### ISSUE THREAD

**Issue by kteare** [hughrun/ghost-to-wp#2]
I created the Ghost Pro json and tried to import. Wordpress imported 16 from 95 posts and then finished. I repeated to check and the same thing. Any ideas?

**Comment by hughrun** [comment]
Hey @kteare this hasn't really been updated for a few years. It's possible the recent release of v4 has changed the structure of Ghost export files.

Can you provide any more information? When you run `ghost-to-wp` does it print "Converting 16 posts..." or "Converting 95 posts..."?

**Comment by kteare** [comment]
I worked around it by installing a local ghost and unlimited rss, and imported to wordpress via an rss reader ;-).

TBH I didn't pay enough attention during the process with your script. So I can't answer your question. I do think that ghost to wordpress is missing a great experience.
