### ISSUE TITLE
Trying this on a json with 1900+ entries

### ISSUE THREAD

**Issue by cgillinger** [hughrun/ghost-to-wp#3]
Hi! 

I'm trying to migrate our blog from Ghost Pro to Wordpress, but for some reason it wont work. The script runs fine, and I get an XML to import to Wordpress. But when importing WP only takes 597 posts and the script reports 1902 entries. 

I'm not sure what the error is, Im thinking it might be the size?

**Comment by hughrun** [comment]
Hey @cgillinger thanks for reporting this. Sounds like the same issue as #2 but I had no further info for that. I haven't touched this script for a year or so and I'm aware Ghost recently release version 4, so I suspect the structure of the export files has changed with the new version and that's what is causing the problem. Happy to take a look at this but I'll be away from my computer for the next week.

If you're able to provide any further info (e.g. a snippet of the original JSON for both a post that is imported and a post that is not; and/or any discernable pattern in terms of which post are and are not exported correctly) that would be helpful in tracking down the problem.

**Comment by cgillinger** [comment]
Absolutely. I could send you the entire json if that would help you, that way you would get both those 597 that works and all the rest as well?

Cheers,
C

**Comment by cgillinger** [comment]
Json attached!

**Comment by hughrun** [comment]
Thanks for the file @cgillinger - can you please upgrade to `v1.3.0` (should be able to do this with `npm`), check the new README, and ideally also follow the section on images? You _should_ be able to now migrate all of your posts, with updated image links, and then transfer your image directory to `wp-content/uploads/` - but I don't have my own Ghost site to test this with.

Let me know how you go - I tested it with a locally installed WordPress and it seems to work now, but would be good to get confirmation, especially re the new image migration functionality.

The basic problem seems to have been an issue with how the script dealt with various line endings, fairly sure that's fixed now.

**Comment by cgillinger** [comment]
> Thanks for the file @cgillinger - can you please upgrade to `v1.3.0` (should be able to do this with `npm`), check the new README, and ideally also follow the section on images? You _should_ be able to now migrate all of your posts, with updated image links, and then transfer your image directory to `wp-content/uploads/` - but I don't have my own Ghost site to test this with.
> 
> Let me know how you go - I tested it with a locally installed WordPress and it seems to work now, but would be good to get confirmation, especially re the new image migration functionality.
> 
> The basic problem seems to have been an issue with how the script dealt with various line endings, fairly sure that's fixed now.

Will do! Just have to wait for Ghost to send us the image archive. As per their support papers there is no way for us to export images, you have to request them. As soon as that is done, I'll get back to you on our progress.

Again, thousand thanks for the help!

/C

**Comment by cgillinger** [comment]
Ok, the script works, and it appears everyhing is converted ok. But for some reason I cant get images to work. They are in the right place, but for some reason Wordpress doesn't recognise them.

I'll do a bit more testing and get back to you.

EDIT: NVM, seem to have solved most of it. I do find some images that the script seem to have skipped updating the url to the one given when issuing the command. Not sure why.

Eg, path I wanted was:
http://localhost/wordpress//wp-content/uploads/2019/09/IMG_20190514_084340.jpg

Bit what I got for some of the pics was:
https://cyklistbloggen.ghost.io/wp-content/uploads/2013/09/541386_624843067537581_1400012140_n.jpg

Not sure why this happened. (The original domain is cyklistbloggen.se)

And solved it by installing a search and replace plugin, and just replacing the wrong url.

So, problem solved, site migrated! Thank you for all your help!


/C

**Comment by hughrun** [comment]
Thanks for reporting back! I might play around with images for a cleaner migration, but glad this has fixed your issue.
